type: object
properties:
  id:
    type: integer
  price:
    type: number
    format: double
  name:
    type: string
  image_url:
    type: string
  description:
    type: string
  category_id:
    type: integer
  variants:
    type: array
    items:
      : './Product_Variant.yaml'
  ingredients:
    type: array
    items:
      : './Ingredient.yaml'
